### PR TITLE
Augment HDF5 with host timestamps and MSG_PRINTs

### PR DESCRIPTION
**Pull request by henryhallam**
@fnoble

### CODE REVIEW

**Comment by henryhallam** [comment]
@mookerji oops

**Comment by fnoble** [comment]
s/hosttime/delta ? otherwise, lgtm

**Comment by henryhallam** [comment]
'delta' is too ambiguous IMO

**Comment by mookerji** [comment]
Rebased and updated and now merged separately as #30 . Danke!

**Pull request closed without merging**
